### ISSUE TITLE
matfile 0.3.1 contains code that will be rejected by a future version of Rust: nom v6.1.2

### ISSUE THREAD

**Issue by klispap** [dthul/matfile#4]
Hi, 

Thank you for creating such a useful crate!

Recently, I started receiving the following warning when I build my projects having matfile 0.3.1 as dependency:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1``
```

I noticed that you already updated matfile repository to support nom v7 with the commit b81374d.

I would appreciate if you can officially publish a new version at crates.io with the nom v7 support.

I am more than happy to help with anything needed to make a new release possible!

Thank you!

**Comment by dthul** [comment]
Thanks for pointing it out!
I will take a look at the state of nom v7 support later today, and release a new version if everything looks good.

**Comment by dthul** [comment]
The new version should be available from crates.io now.

**Comment by klispap** [comment]
Thank you for the new release!
The issue is not reproducing any more!
